site_name: Nombre del sitio
site_description: 'Aqui va la descripcion del sitio'
site_author: 'SPS'
docs_dir: docs/
repo_name: 'CarlosBrunoE/devops_mkdocs'
repo_url: 'https://github.com/CarlosBrunoE/devops_mkdocs'
nav:
    - Home: index.md
theme:
  name: 'material'
